config/routes.rb
Rails.application.routes.draw do
  get 'activity/index'

  resources :groups do
    resources :class_students
    resources :posts do
      resources :comments
    end
    resources :assignments do
      resources :assignment_submissions 
    end
    resources :activities do
      resources :activity_submissions
    end
  end

  get '/profile', to: 'profiles#index'
  get '/feed', to: 'profiles#feed'
  post 'create2', to: 'posts#create2'
  post 'create_2', to: 'comments#create2'
  devise_scope :user do
    get "/sign_out" => "users/sessions#destroy" 
    authenticated :user do
      namespace :users do
        get 'classes/index', as: :classes
      end
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root :to => "profiles#feed"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'classpage', to: 'html_pages#classpage'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :group
  has_many :questions, inverse_of: :activity
  accepts_nested_attributes_for :questions
  has_many :activity_submissions

  validates_presence_of :title
  validates_presence_of :instructions
end

app/models/activity_submission.rb
class ActivitySubmission < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  has_many :answers, inverse_of: :activity_submission
  accepts_nested_attributes_for :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :activity_submission
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :group
  has_many :assignment_submissions, dependent: :delete_all

  validates :title, presence: true
end

app/models/class_student.rb
class ClassStudent < ApplicationRecord

    belongs_to :group
    belongs_to :user
    validates :user_id, uniqueness: { scope: :group_id, message: "Student already exists for this class." }

    enum statuses: {
		'Pending': 'Pending',
		'Joined': 'Joined'
	}

  def my_submission(activity)
    student = User.where(id: self.user_id).first
    submission = student.activity_submissions.where(activity_id: activity.id)
  end

  def my_score(activity)
    student = User.where(id: self.user_id).first
    score = student.activity_submissions.where(activity_id: activity.id).first.answers.sum(:grading)
    overall = activity.questions.sum(:grading)

    return (score.to_s + " / " + overall.to_s)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content , presence: true
  belongs_to :user
  belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord
    validates :name , presence: true 
    validates :description, presence: true

    mount_uploader :img, ImgUploader
    belongs_to :user
    has_many :class_students
    has_many :posts
    has_many :assignments, dependent: :delete_all
    has_many :activities
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true 

  belongs_to :user
  belongs_to :group
  has_many :comments
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :role, presence: true
  mount_uploader :img, ImgUploader
  has_many :groups
  has_many :class_students

  has_many :activities
  has_many :activity_submissions
  belongs_to :class_student, optional: true
  has_many :posts
  enum roles: { admin: "admin", teacher: "teacher", student: "student", guardian: "guardian"}

  def fullname
    "#{self.first_name} #{self.middle_name} #{self.last_name}"
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_group 
  before_action :set_assignment, only: %i[ show edit update destroy ]


  # GET /assignments or /assignments.json
  def index
    @assignments = @group.assignments
  end

  # GET /assignments/1 or /assignments/1.json
  def show
    @assignment_submission = @assignment.assignment_submissions.build
    @assignment_submissions = @assignment.assignment_submissions
  end

  # GET /assignments/new
  def new
    authorize Assignment, :new?
    @assignment = @group.assignments.build
  end

  # GET /assignments/1/edit
  def edit
    authorize Assignment, :edit?
  end

  # POST /assignments or /assignments.json
  def create
    @assignment = @group.assignments.build(assignment_params)
    
    respond_to do |format|
      if @assignment.save
        @post = @group.posts.new(content: "Created a new assignment " + @assignment.title, user_id: current_user.id)
        @post.save
        format.html { redirect_to group_assignment_path(@group, @assignment), notice: "Assignment was successfully created." }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to group_assignment_path(@group), notice: "Assignment was successfully updated." }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1 or /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to group_assignments_path(@group), notice: "Assignment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_group
      @group = Group.find(params[:group_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = @group.assignments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:title, :instructions, :group_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
    # GET /groups or /groups.json
    def index
      @user = current_user
      @posts = Post.all
      @groups = @user.groups
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def self.list(user)
    if user.role == 'teacher'
      @groups = user.groups
    elsif user.role == 'student'
      @groups = ClassStudent.where(user_id: user.id).map{|x| x.group}.uniq
    else
      @groups = Group.all
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/assignments/_form.html.haml
= form_with(model: [@group, @assignment], local: true) do |f|
  - if @assignment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@assignment.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @assignment.errors.full_messages.each do |msg|
          %li= msg
  .w-full.bg-white.rounded-lg.mx-auto.mt-16.flex.overflow-hidden.rounded-b-none.flex-col.p-8
    .w-full
      .md:flex.items-center
        .w-full.flex.flex-col.px-2.py-4
          = f.label :title, :class => "text-sm text-gray-600"
          = f.text_field :title, :class => "mt-2 border-2 border-gray-200 px-3 py-2 block w-full rounded-lg text-base text-gray-900 focus:outline-none focus:border-indigo-500"
            
      .md:flex.items-center
        .w-full.flex.flex-col.px-2.py-4
          = f.label :instructions, :class => "text-sm text-gray-600"
          = f.text_field :instructions, :class => "mt-2 border-2 border-gray-200 px-3 py-2 block w-full rounded-lg text-base text-gray-900 focus:outline-none focus:border-indigo-500", :placeholder => "Class description", rows: "3"
          
    .md:flex-1.px-3.text-center.md:text-right.mt-16
      %button.bg-my-silver.hover:bg-blue-700.text-white.font-bold.py-2.px-4.rounded Cancel
      %input.bg-my-blue.hover:bg-my-light-blue.text-white.font-bold.py-2.px-4.rounded{type: "submit", value: "Create"}/

app/views/assignments/_index.html.haml
%div{class:"flex flex-col md:flex-row items-center justify-between w-full mt-10"}
  %h1.text-2xl.font-bold.text-my-blue.px-6.md:px-0 Assignments
  - if current_user.role == 'teacher'
    = link_to new_group_assignment_path(@group), :class => "text-white flex self-center px-8 py-2 rounded bg-my-blue hover:bg-my-blue hover:opacity-80 flex items-center justify-center transition duration-250" do 
      %span{class: "text-white text-base"} Create Assignment 
  
.w-full.mt-10
  %table#assignments.stripe.hover.w-full.mt-10.py-8
    %thead.bg-my-light-blue.w-full
      %tr
        %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Title
        %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Instructions
        %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Submissions
        %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Actions

    %tbody{class: "bg-white w-full"}
      - for assignment in @group.assignments
        %tr
          %td.py-4.px-6.text-sm.font-medium.whitespace-nowrap
            =assignment.title
          %td.py-4.px-6.text-sm.font-medium.whitespace-nowrap
            =assignment.instructions
          %td.px-6.py-4.whitespace-no-wrap.border-b.border-gray-200.text-sm.leading-5
            = assignment.assignment_submissions.count
          %td.px-6.py-4.whitespace-no-wrap.border-b.border-gray-200.text-sm.leading-5.flex.gap-4
            =link_to "View / Submit", group_assignment_path(@group, assignment) 


:javascript
  var table = $('#assignments').DataTable( {
    responsive: true
  } )
  .columns.adjust()
  .responsive.recalc();

app/views/assignments/edit.html.haml
%h1 Editing assignment

= render 'form'

= link_to 'Show', [@group, @assignment]
\|
= link_to 'Back', group_assignments_path(@group)

app/views/assignments/index.html.haml
.container.mx-auto.w-full.mt-8.py-10.min-w-full.sm:px-6.lg:px-8.bg-white.rounded
  
  %p#notice= notice
  %div{class:"flex items-between justify-center gap-2 w-full my-4"}
    %div{class: "flex flex-col gap-2 w-full text-3xl"}
      %span{class: "text-3xl text-my-blue font-bold"}= "#{@group.name} (#{@group.user.fullname})"
      -# %div{class: "flex flex-col md:flex-row text-xl gap-3"}
      -#   %span{class: "text-gray-500"} Teacher:
      -#   %span= @teacher.fullname
      %div{class: "flex flex-col md:flex-row text-xl gap-3"}
        %span{class: "text-base text-gray-600"}Description: 
        %span{class: "text-base"}= @group.description

  %ul.flex.border-b.border-light-blue.text-sm.font-medium.text-my-blue.px-4.md:px-0.mt-8.w-auto
    %li.font-bold.hover:text-my-pink
      %a.py-4.inline-block.bold.hover:bg-my-pink.hover:text-my-blue.p-4{href: "#{group_path(@group)}#_"} Students
    %li.font-bold.hover:text-my-pink
      %a.py-4.inline-block.bold.hover:bg-my-pink.hover:text-my-blue.p-4{href: "#{group_activities_path(@group)}#_"} Activities
    %li.font-bold.text-my-blue.border-b-2.border-my-pink.bg-my-pink
      %a.py-4.inline-block.bold.hover:bg-my-pink.hover:text-my-blue.p-4{href: "#{group_assignments_path(@group)}#_"} Assignments
  

= render :partial => 'layouts/table_links'
.flex.flex-col.md:flex-row.items-center.justify-between.w-full.mt-8
  %h1.text-2xl.font-bold.text-my-blue.px-6.md:px-0 Assignments
  = link_to new_group_assignment_path(@group), :class => "text-white flex self-center px-8 py-2 rounded bg-my-blue hover:bg-my-blue hover:opacity-80 flex items-center justify-center transition duration-250" do 
    %span{class: "text-white text-base"} Create Assignment 
  
.w-full.mt-10
  %table#assignments.stripe.hover.w-full.mt-10.py-8
    %thead.bg-my-light-blue.dark:bg-white
      %tr
        %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Title
        %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Instructions
        %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Submissions
        %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Actions

    %tbody{class: "bg-white"}
      - for assignment in @group.assignments
        %tr
          %td.py-4.px-6.text-sm.font-medium.whitespace-nowrap
            =assignment.title
          %td.py-4.px-6.text-sm.font-medium.whitespace-nowrap
            =assignment.instructions
          %td.px-6.py-4.whitespace-no-wrap.border-b.border-gray-200.text-sm.leading-5
            = assignment.assignment_submissions.count
          %td.px-6.py-4.whitespace-no-wrap.border-b.border-gray-200.text-sm.leading-5.flex.gap-4
            =link_to "View / Submit", group_assignment_path(@group, assignment) 


:javascript
  var table = $('#assignments').DataTable( {
    responsive: true
  } )
  .columns.adjust()
  .responsive.recalc();

app/views/assignments/new.html.haml
%span{class: "text-3xl text-my-blue font-bold"} Create Assignment

= render 'form'

%div{class:"bg-white p-8"}
  = link_to 'Back Group', group_path(@group), :class => "w-40 flex self-center px-8 py-2 rounded bg-my-blue hover:bg-my-blue hover:bg-my-blue hover:opacity-80 flex items-center justify-center transition duration-250", :style => "color: white"

app/views/assignments/show.html.haml
%div{class: "container mx-auto px-6 py-8 gap-2 flex flex-col w-full  justify-center items-center md:items-start"}

  %p#notice= notice
  %div{class:"flex items-between justify-center gap-2 w-full bg-white p-8 rounded"}
    %div{class: "flex flex-col gap-4 w-full items-start text-3xl"}
      %span{class: "text-xl border-b pb-2 border-gray-300"}= @assignment.group.name
      %div{class: "flex text-xl gap-3 justify-center md:justify-start items-center"}
        %span{class: "text-lg text-gray-500"} Assignment Title: 
        %span{class: "text-lg"}= @assignment.title
      %div{class: "flex flex-col md:gap-3 md:flex-row text-xl justify-center md:justify-start items-center"}
        %span{class: "text-base text-gray-500"}Instructions: 
        %span{class: "text-base"}= @assignment.instructions 
    - if current_user.role == "teacher"
      = link_to 'Edit Assignment', edit_group_assignment_path(@group, @assignment), :class => "whitespace-nowrap self-end bg-my-blue flex items-center justify-center rounded text-base py-1 px-4 text-white hover:bg-my-blue hover:opacity-75 transition-opacity duration-200", :style=>'color:#FFFFFF;'
    
  - if current_user.role == "student"
    = render 'assignment_submissions/form'
  - elsif current_user.role == "teacher"
    = render 'assignment_submissions/aslist'
  - else

  = link_to 'Back to Group', group_path(@group), :class => "cursor-pointer my-4 bg-my-blue flex items-center justify-center rounded text-base py-1 px-4 text-white hover:bg-my-blue hover:opacity-75 transition-opacity duration-200", :style=>'color:#FFFFFF;'