config/routes.rb
Rails.application.routes.draw do
  get 'activity/index'

  resources :groups do
    resources :class_students
    resources :posts do
      resources :comments
    end
    resources :assignments do
      resources :assignment_submissions 
    end
    resources :activities do
      resources :activity_submissions
    end
  end

  get '/profile', to: 'profiles#index'
  get '/feed', to: 'profiles#feed'
  post 'create2', to: 'posts#create2'
  post 'create_2', to: 'comments#create2'
  devise_scope :user do
    get "/sign_out" => "users/sessions#destroy" 
    authenticated :user do
      namespace :users do
        get 'classes/index', as: :classes
      end
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root :to => "profiles#feed"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'classpage', to: 'html_pages#classpage'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :group
  has_many :questions, inverse_of: :activity
  accepts_nested_attributes_for :questions
  has_many :activity_submissions

  validates_presence_of :title
  validates_presence_of :instructions
end

app/models/activity_submission.rb
class ActivitySubmission < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  has_many :answers, inverse_of: :activity_submission
  accepts_nested_attributes_for :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :activity_submission
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :group
  has_many :assignment_submissions, dependent: :delete_all

  validates :title, presence: true
end

app/models/class_student.rb
class ClassStudent < ApplicationRecord

    belongs_to :group
    belongs_to :user
    validates :user_id, uniqueness: { scope: :group_id, message: "Student already exists for this class." }

    enum statuses: {
		'Pending': 'Pending',
		'Joined': 'Joined'
	}

  def my_submission(activity)
    student = User.where(id: self.user_id).first
    submission = student.activity_submissions.where(activity_id: activity.id)
  end

  def my_score(activity)
    student = User.where(id: self.user_id).first
    score = student.activity_submissions.where(activity_id: activity.id).first.answers.sum(:grading)
    overall = activity.questions.sum(:grading)

    return (score.to_s + " / " + overall.to_s)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content , presence: true
  belongs_to :user
  belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord
    validates :name , presence: true 
    validates :description, presence: true

    mount_uploader :img, ImgUploader
    belongs_to :user
    has_many :class_students
    has_many :posts
    has_many :assignments, dependent: :delete_all
    has_many :activities
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true 

  belongs_to :user
  belongs_to :group
  has_many :comments
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :role, presence: true
  mount_uploader :img, ImgUploader
  has_many :groups
  has_many :class_students

  has_many :activities
  has_many :activity_submissions
  belongs_to :class_student, optional: true
  has_many :posts
  enum roles: { admin: "admin", teacher: "teacher", student: "student", guardian: "guardian"}

  def fullname
    "#{self.first_name} #{self.middle_name} #{self.last_name}"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :set_post, except: %i[ create2 ]
  before_action :set_group, except: %i[ create2 ]
  # GET /comments or /comments.json
  def index
    @comments = @post.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @post.comments << @comment

    respond_to do |format|
      if @comment.save
        format.html { redirect_to group_post_path(@group, @post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def create2
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to '/feed', notice: "Comment was successfully created." }
      else
        format.html { redirect_to '/feed', notice: "Comment was not created." }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end
    
    def set_group 
      @group = Group.find(params[:group_id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
    # GET /groups or /groups.json
    def index
      @user = current_user
      @posts = Post.all
      @groups = @user.groups
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def self.list(user)
    if user.role == 'teacher'
      @groups = user.groups
    elsif user.role == 'student'
      @groups = ClassStudent.where(user_id: user.id).map{|x| x.group}.uniq
    else
      @groups = Group.all
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/comments/_form.html.haml
= form_for [ @group, @post, @comment ] do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content
  .field
    -# = f.label :user_id
    = f.hidden_field :user_id, value: current_user.id
  .actions
    = f.submit 'Save'

app/views/comments/_form_all.html.haml
.w-full
  = form_with scope: :comment, url: create_2_path do |f|
    - if @comment.errors.any?
      #error_explanation
        %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
        %ul
          - @comment.errors.full_messages.each do |msg|
            %li= msg
    .flex.items-center.border-b.border-teal-500.py-2
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :post_id, value: info.id
      = f.text_area :content, :class => "appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none", :placeholder => "Write a comment"
      = f.submit 'Comment', :class => "flex-shrink-0 bg-my-blue hover:bg-my-blue hover:opacity-75 transition-opacity duration-200 text-sm text-white py-1 px-2 rounded"

      

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th Content
      %th Post
      %th User
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.content
        %td= comment.post_id
        %td= comment.user_id
        -# %td= link_to 'Show', comment
        -# %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', group_post_comments_path([@group , @post])

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', group_path(@group)

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @comment.content
%p
  %b Post:
  = @comment.post_id
%p
  %b User:
  = @comment.user_id

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path