config/routes.rb
Rails.application.routes.draw do
  get 'activity/index'

  resources :groups do
    resources :class_students
    resources :posts do
      resources :comments
    end
    resources :assignments do
      resources :assignment_submissions 
    end
    resources :activities do
      resources :activity_submissions
    end
  end

  get '/profile', to: 'profiles#index'
  get '/feed', to: 'profiles#feed'
  post 'create2', to: 'posts#create2'
  post 'create_2', to: 'comments#create2'
  devise_scope :user do
    get "/sign_out" => "users/sessions#destroy" 
    authenticated :user do
      namespace :users do
        get 'classes/index', as: :classes
      end
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root :to => "profiles#feed"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'classpage', to: 'html_pages#classpage'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :group
  has_many :questions, inverse_of: :activity
  accepts_nested_attributes_for :questions
  has_many :activity_submissions

  validates_presence_of :title
  validates_presence_of :instructions
end

app/models/activity_submission.rb
class ActivitySubmission < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  has_many :answers, inverse_of: :activity_submission
  accepts_nested_attributes_for :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :activity_submission
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :group
  has_many :assignment_submissions, dependent: :delete_all

  validates :title, presence: true
end

app/models/class_student.rb
class ClassStudent < ApplicationRecord

    belongs_to :group
    belongs_to :user
    validates :user_id, uniqueness: { scope: :group_id, message: "Student already exists for this class." }

    enum statuses: {
		'Pending': 'Pending',
		'Joined': 'Joined'
	}

  def my_submission(activity)
    student = User.where(id: self.user_id).first
    submission = student.activity_submissions.where(activity_id: activity.id)
  end

  def my_score(activity)
    student = User.where(id: self.user_id).first
    score = student.activity_submissions.where(activity_id: activity.id).first.answers.sum(:grading)
    overall = activity.questions.sum(:grading)

    return (score.to_s + " / " + overall.to_s)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content , presence: true
  belongs_to :user
  belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord
    validates :name , presence: true 
    validates :description, presence: true

    mount_uploader :img, ImgUploader
    belongs_to :user
    has_many :class_students
    has_many :posts
    has_many :assignments, dependent: :delete_all
    has_many :activities
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true 

  belongs_to :user
  belongs_to :group
  has_many :comments
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :role, presence: true
  mount_uploader :img, ImgUploader
  has_many :groups
  has_many :class_students

  has_many :activities
  has_many :activity_submissions
  belongs_to :class_student, optional: true
  has_many :posts
  enum roles: { admin: "admin", teacher: "teacher", student: "student", guardian: "guardian"}

  def fullname
    "#{self.first_name} #{self.middle_name} #{self.last_name}"
  end
end

app/controllers/activity_submissions_controller.rb
class ActivitySubmissionsController < ApplicationController
  before_action :set_group, only: %i[ show new create ]
  before_action :set_activity, only: %i[ show new create ]
  before_action :set_activity_submission, only: %i[ show edit update destroy ]

  # GET /activity_submissions or /activity_submissions.json
  def index
    @activity_submissions = ActivitySubmission.all
  end

  # GET /activity_submissions/1 or /activity_submissions/1.json
  def show
    @questions = @activity.questions
    @answers = @activity_submission.answers
  end

  # GET /activity_submissions/new
  def new
    @activity_submission = @activity.activity_submissions.build
    @questions = @activity.questions
    @activity.questions.count.times { @activity_submission.answers.build }
  end

  # GET /activity_submissions/1/edit
  def edit
  end

  # POST /activity_submissions or /activity_submissions.json
  def create
    @activity_submission = @activity.activity_submissions.build(activity_submission_params)

    @activity.questions.each_with_index {|question, index|
      if @activity_submission.answers[index].answer == question.correct_answer
        @activity_submission.answers[index].grading = 1
      else
        @activity_submission.answers[index].grading = 0
      end
    }

    respond_to do |format|
      if @activity_submission.save
        format.html { redirect_to group_activity_path(:id => @activity.id), notice: "Activity submission was successfully created." }
        format.json { render :show, status: :created, location: @activity_submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_submissions/1 or /activity_submissions/1.json
  def update
    respond_to do |format|
      if @activity_submission.update(activity_submission_params)
        format.html { redirect_to activity_submission_url(@activity_submission), notice: "Activity submission was successfully updated." }
        format.json { render :show, status: :ok, location: @activity_submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_submissions/1 or /activity_submissions/1.json
  def destroy
    @activity_submission.destroy

    respond_to do |format|
      format.html { redirect_to activity_submissions_url, notice: "Activity submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_activity
      @activity = Activity.find(params[:activity_id])
    end

    def set_activity_submission
      @activity_submission = ActivitySubmission.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def activity_submission_params
      params.require(:activity_submission).permit(:user_id, :instructions, answers_attributes: [:id, :question_id, :answer, :grading])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/activity_submissions_helper.rb
module ActivitySubmissionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def self.list(user)
    if user.role == 'teacher'
      @groups = user.groups
    elsif user.role == 'student'
      @groups = ClassStudent.where(user_id: user.id).map{|x| x.group}.uniq
    else
      @groups = Group.all
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/activity_submissions/_form.html.haml
%div{ :class => "mt-10 sm:mt-0" }
  %div{ :class => "flex justify-center" }
    %div{ :class => "mt-5 md:mt-0 md:col-span-2", :style => "min-width: 500px" }
      = form_with model: [ @group, @activity, @activity_submission ] do |f|
        - if @activity_submission.errors.any?
          #error_explanation
            %h2= "#{pluralize(@activity_submission.errors.count, "error")} prohibited this activity_submission from being saved:"
            %ul
              - @activity_submission.errors.full_messages.each do |msg|
                %li= msg
        
        = f.hidden_field :user_id, value: current_user.id

        = f.fields_for :answers do |answers_form|
          %div{ :class => "shadow overflow-hidden sm:rounded-md py-1" }
            %div{ :class => "px-4 py-5 bg-white space-y-6 sm:p-6" }
              %fieldset
                %div
                  %legend{ :class => "text-base font-medium text-gray-900" }
                    Question #{(answers_form.index + 1)}

                  .py-2
                    .border-t.border-gray-200
                  
                  %p{ :class => "text-sm text-gray-700" }
                    = @questions[answers_form.index].query_question
                  
                  = answers_form.hidden_field :question_id, value: @questions[answers_form.index].id

                %div{ :class => "mt-4 space-y-4" }
                  %div{ :class => "flex items-center" }
                    = answers_form.radio_button :answer, "true", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                    = answers_form.label :answer_true, "True", class: "ml-3 block text-sm font-medium text-gray-700"

                  %div{ :class => "flex items-center" }
                    = answers_form.radio_button :answer, "false", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                    = answers_form.label :answer_false, "False", class: "ml-3 block text-sm font-medium text-gray-700"

                = answers_form.hidden_field :grading, value: 0

        %div{ :class => "px-4 py-3 bg-gray-50 text-right sm:px-6" }
          = f.submit 'Submit', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          -# <button type="submit" :class =>  }Save

app/views/activity_submissions/edit.html.haml
%h1 Editing activity_submission

= render 'form'

= link_to 'Show', @activity_submission
\|
= link_to 'Back', activity_submissions_path

app/views/activity_submissions/index.html.haml
%h1 Listing activity_submissions

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @activity_submissions.each do |activity_submission|
      %tr
        %td= link_to 'Show', activity_submission
        %td= link_to 'Edit', edit_activity_submission_path(activity_submission)
        %td= link_to 'Destroy', activity_submission, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Activity submission', new_activity_submission_path

app/views/activity_submissions/new.html.haml
%h1 New activity_submission

= render 'form'

= link_to 'Back', group_activity_path(:id => @activity.id)

app/views/activity_submissions/show.html.haml
%div{ :class => "mt-10 sm:mt-0" }
  %div{ :class => "flex justify-center" }
    = link_to "Back", group_activity_path(@group, @activity),  :class => "absolute left-2 my-4 bg-my-blue flex items-center justify-center rounded text-base py-1 px-12 text-white hover:bg-my-blue hover:opacity-75 transition-opacity duration-200", :style=>'color:#FFFFFF;'
    %div{ :class => "mt-5 md:mt-0 md:col-span-2", :style => "min-width: 500px" }
      - @questions.each.with_index do |question, index|
        %div{ :class => "shadow overflow-hidden sm:rounded-md py-1" }
          %div{ :class => "px-4 py-5 bg-white space-y-6 sm:p-6" }
            %fieldset
              %div
                %legend{ :class => "text-base font-medium text-gray-900" }
                  Question #{(index + 1)}: #{question.correct_answer == @answers[index].answer ? "Correct" : "Incorrect"}
                
                .py-2
                  .border-t.border-gray-200
                
                %p{ :class => "text-sm text-gray-700" }
                  = question.query_question
                
                %div{ :class => "mt-4 space-y-4" }
                  - if question.correct_answer == true
                    - if @answers[index].answer == true
                      %div{ :class => "flex items-center border-2 border-green-500 py-2" }
                        %input{ :type => 'radio', :name => index, :value => '1', :checked => true, :class => "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" }
                        True
                        -# = answers_form.radio_button :answer, "true", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                        -# = answers_form.label :answer_true, "True", class: "ml-3 block text-sm font-medium text-gray-700"

                      %div{ :class => "flex items-center" }
                        %input{ :type => 'radio', :name => index, :value => '1', :class => "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" }
                          False
                    
                    - else
                      %div{ :class => "flex items-center border-2 border-red-500 py-2" }
                        %input{ :type => 'radio', :name => index, :value => '1', :class => "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" }
                        True
                        -# = answers_form.radio_button :answer, "true", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                        -# = answers_form.label :answer_true, "True", class: "ml-3 block text-sm font-medium text-gray-700"

                      %div{ :class => "flex items-center border-2 border-green-500 py-2" }
                        %input{ :type => 'radio', :name => index, :value => '1', :checked => true, :class => "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" }
                          False
                  - else
                    - if @answers[index].answer == false
                      %div{ :class => "flex items-center" }
                        %input{ :type => 'radio', :name => index, :value => '1', :class => "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" }
                        True
                        -# = answers_form.radio_button :answer, "true", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                        -# = answers_form.label :answer_true, "True", class: "ml-3 block text-sm font-medium text-gray-700"

                      %div{ :class => "flex items-center border-2 border-green-500 py-2" }
                        %input{ :type => 'radio', :name => index, :value => '1', :checked => true, :class => "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" }
                          False
                    
                    - else
                      %div{ :class => "flex items-center border-2 border-red-500 py-2" }
                        %input{ :type => 'radio', :name => index, :value => '1', :checked => true, :class => "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" }
                        True
                        -# = answers_form.radio_button :answer, "true", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                        -# = answers_form.label :answer_true, "True", class: "ml-3 block text-sm font-medium text-gray-700"

                      %div{ :class => "flex items-center border-2 border-green-500 py-2" }
                        %input{ :type => 'radio', :name => index, :value => '1', :class => "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" }
                          False

     
      -#   = f.submit 'Submit', 
      -#   -# <button type="submit" :class =>  }Save                
                    -# = answers_form.radio_button :answer, "false", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                    -# = answers_form.label :answer_false, "False", class: "ml-3 block text-sm font-medium text-gray-700"

      -# = f.fields_for :answers do |answers_form|
      -#   %div{ :class => "shadow overflow-hidden sm:rounded-md py-1" }
      -#     %div{ :class => "px-4 py-5 bg-white space-y-6 sm:p-6" }
      -#       %fieldset
      -#         %div
      -#           %legend{ :class => "text-base font-medium text-gray-900" }
      -#             Question #{(answers_form.index + 1)}

      -#           .py-2
      -#             .border-t.border-gray-200
                
      -#           %p{ :class => "text-sm text-gray-700" }
      -#             = @questions[answers_form.index].query_question
                
      -#           = answers_form.hidden_field :question_id, value: @questions[answers_form.index].id

      -#         %div{ :class => "mt-4 space-y-4" }
      -#           %div{ :class => "flex items-center" }
      -#             = answers_form.radio_button :answer, "true", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
      -#             = answers_form.label :answer_true, "True", class: "ml-3 block text-sm font-medium text-gray-700"

      -#           %div{ :class => "flex items-center" }
      -#             = answers_form.radio_button :answer, "false", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
      -#             = answers_form.label :answer_false, "False", class: "ml-3 block text-sm font-medium text-gray-700"

      -#         = answers_form.hidden_field :grading, value: 0

      -# %div{ :class => "px-4 py-3 bg-gray-50 text-right sm:px-6" }
      -#   = f.submit 'Submit', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
      -#   -# <button type="submit" :class =>  }Save