config/routes.rb
Rails.application.routes.draw do
  get 'activity/index'

  resources :groups do
    resources :class_students
    resources :posts do
      resources :comments
    end
    resources :assignments do
      resources :assignment_submissions 
    end
    resources :activities do
      resources :activity_submissions
    end
  end

  get '/profile', to: 'profiles#index'
  get '/feed', to: 'profiles#feed'
  post 'create2', to: 'posts#create2'
  post 'create_2', to: 'comments#create2'
  devise_scope :user do
    get "/sign_out" => "users/sessions#destroy" 
    authenticated :user do
      namespace :users do
        get 'classes/index', as: :classes
      end
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root :to => "profiles#feed"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'classpage', to: 'html_pages#classpage'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :group
  has_many :questions, inverse_of: :activity
  accepts_nested_attributes_for :questions
  has_many :activity_submissions

  validates_presence_of :title
  validates_presence_of :instructions
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_group, only: %i[ index show new create ]
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = @group.activities
  end

  # GET /activities/1 or /activities/1.json
  def show
    @questions = @activity.questions
    @count = @questions.count
    @points = @questions.sum(:grading)
    @submission = @activity.activity_submissions.where(user_id: current_user.id).first
    @score = @submission != nil ? @submission.answers.sum(:grading) : 0
    @students = @group.class_students
  end

  # GET /activities/new
  def new
    @activity = @group.activities.build
    5.times { @activity.questions.build }
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = @group.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        @post = @group.posts.new(content: "Created a new activity " + @activity.title, user_id: current_user.id)
        @post.save
        format.html { redirect_to group_path(@group), notice: "#{@activity.title} was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:group_id])
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = @group.activities.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:title, :instructions, questions_attributes: [:id, :query_question, :correct_answer, :grading])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/views/activities/_form.html.haml
%div{ :class => "mt-10 sm:mt-0" }
  %div{ :class => "flex justify-center" }
    %div{ :class => "mt-5 md:mt-0 md:col-span-2", :style => "min-width: 500px" }
      = form_with model: [ @group, @activity ] do |f|
        - if @activity.errors.any?
          #error_explanation
            %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
            %ul
              - @activity.errors.full_messages.each do |msg|
                %li= msg
        
        %div{ :class => "py-1"}
          = f.label :title, :class => "block text-sm font-medium text-gray-700"
          .mt-1.relative.rounded-md.shadow-sm
            = f.text_field :title, :class => "focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
        
        %div{ :class => "py-1"}
          = f.label :instructions, :class => "block text-sm font-medium text-gray-700"
          .mt-1.relative.rounded-md.shadow-sm
            = f.text_area :instructions, :class => "focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-3 sm:text-sm border-gray-300 rounded-md", rows: "3"

        = f.fields_for :questions do |questions_form|
          %div{ :class => "shadow overflow-hidden sm:rounded-md py-1" }
            %div{ :class => "px-4 py-5 bg-white space-y-6 sm:p-6" }
              %fieldset
                %div
                  %legend{ :class => "text-base font-medium text-gray-900" }
                    Question #{(questions_form.index + 1)}

                  .py-2
                    .border-t.border-gray-200
                  
                  .mt-1.relative.rounded-md.shadow-sm
                    = questions_form.text_area :query_question, :class => "focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-3 sm:text-sm border-gray-300 rounded-md", rows: "2"
                
                %div{ :class => "mt-4 space-y-4" }
                  = questions_form.label :correct_answer, :class => "block text-sm font-medium text-gray-700"
                  %div{ :class => "flex items-center" }
                    = questions_form.radio_button :correct_answer, "true", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                    = questions_form.label :correct_answer_true, "True", class: "ml-3 block text-sm font-medium text-gray-700"

                  %div{ :class => "flex items-center" }
                    = questions_form.radio_button :correct_answer, "false", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300"
                    = questions_form.label :correct_answer_false, "False", class: "ml-3 block text-sm font-medium text-gray-700"

                %div{ :class => "py-3"}
                  = questions_form.label :grading, :class => "block text-sm font-medium text-gray-700"
                  .mt-1.relative.rounded-md.shadow-sm
                    = questions_form.text_field :grading, :class => "focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md", :value => 1

        %div{ :class => "px-4 py-3 bg-gray-50 text-right sm:px-6" }
          = f.submit 'Submit', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          -# <button type="submit" :class =>  }Save

app/views/activities/_index.html.haml
.flex.flex-wrap.gap-2.py-6
  - @activities.each do |activity|
    .p-6.max-w-sm.bg-white.rounded-lg.border.border-gray-200.shadow-md.dark:bg-gray-800.dark:border-gray-700.flex.flex-col.justify-between
      %div
        %h5.mb-2.text-2xl.font-bold.tracking-tight.text-gray-900.dark:text-white
          = activity.title
        %p.mb-3.font-normal.text-gray-700.dark:text-gray-400
          = activity.instructions
      %div
        = link_to "View", group_activity_path(@group, activity), :class => "text-white flex self-center px-8 py-2 rounded bg-my-blue hover:bg-my-blue hover:opacity-80 flex items-center justify-center transition duration-250", style: "color: white"
  
  - if current_user.role == 'teacher'
    .p-6.max-w-sm.bg-white.rounded-lg.border.border-gray-200.shadow-md.dark:bg-gray-800.dark:border-gray-700.flex.flex-col.justify-between
      %div
        %h5.mb-2.text-2xl.font-bold.tracking-tight.text-gray-900.dark:text-white
          New Activity
      %div
        = link_to "Create", new_group_activity_path(@group), :class => "py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 visited:text-white"

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/new.html.haml
= render 'form'

%div{ :class => "px-4 py-3 text-right sm:px-6 absolute top-20 left-5" }
  = link_to "Back", group_path(@group), class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 visited:text-white"

app/views/activities/show.html.haml
- if current_user.role == "student"
  %div{ :class =>"container flex flex-col mx-auto px-6 py-8 flex flex-col w-full items-center" }
    %div{ :class =>"bg-white shadow overflow-hidden sm:rounded-lg" }
      %div{ :class => "text-right sm:px-6 absolute top-20 left-5" }
        = link_to "Back", group_path(@group),  :class => "absolute left-2 my-4 bg-my-blue flex items-center justify-center rounded text-base py-1 px-12 text-white hover:bg-my-blue hover:opacity-75 transition-opacity duration-200", :style=>'color:#FFFFFF;'

      %div{ :class =>"px-4 py-5 sm:px-6" }
        %h3{ :class =>"text-lg leading-6 font-medium text-gray-900" }
          = @activity.title
      
      %div{ :class =>"border-t border-gray-200" }
        %dl
          %div{ :class =>"bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6" }
            %dt{ :class =>"text-sm font-medium text-gray-500" } Instructions
            %dd{ :class =>"mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" }
              = @activity.instructions
          
          %div{ :class =>"bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6" }
            %dt{ :class =>"text-sm font-medium text-gray-500" } Questions
            %dd{ :class =>"mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" }
              = @count
          
          %div{ :class =>"bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6" }
            %dt{ :class =>"text-sm font-medium text-gray-500" } Points
            %dd{ :class =>"mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" }
              = @points
          
          - if @submission != nil
            %div{ :class =>"bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6" }
              %dt{ :class =>"text-sm font-medium text-gray-500" } Score
              %dd{ :class =>"mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" }
                = @score
          
          %div{ :class =>"px-4 py-3 bg-gray-50 text-right sm:px-6" }
            - if @submission == nil
              = link_to "Take Quiz", new_group_activity_activity_submission_path(:group_id => @group.id,:activity_id => @activity.id), class:"inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 visited:text-white"
            - else
              = link_to "Review Quiz", group_activity_activity_submission_path(@group, @activity, @submission),  :class => "text-white flex self-center px-8 py-2 rounded bg-my-blue hover:bg-my-blue hover:opacity-80 flex items-center justify-center transition duration-250", style: "color: white"
- else
  .container.mx-auto.w-full.mt-8.py-10.min-w-full.sm:px-6.lg:px-8.bg-white.rounded

    %div{class:"flex items-between justify-center gap-2 w-full my-4"}
      %div{class: "flex flex-col gap-2 w-full text-3xl"}
        %span{class: "text-3xl text-my-blue font-bold"}= "#{@activity.title}"
        %div{class: "flex flex-col md:flex-row text-xl gap-3"}
          %span{class: "text-base text-gray-500"}Description: 
          %span{class: "text-base"}= @activity.instructions

      %div{class: "flex justify-center gap-2"}
        -# = link_to "#", :class => "w-40 flex self-center px-7 py-2 rounded bg-my-blue hover:bg-my-blue hover:bg-my-blue hover:opacity-80 flex items-center justify-center transition duration-250" do 
        -#   %span{class: "text-white text-base"} Edit Activity
        = link_to "#", :class => "w-40 flex self-center px-7 py-2 rounded bg-my-blue hover:bg-my-blue hover:bg-my-blue hover:opacity-80 flex items-center justify-center transition duration-250" do 
          %span{class: "text-white text-base"} Delete Activity
        -# = link_to @group, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "w-40 hover:text-white flex gap-2 self-center px-8 w-32 py-2 rounded bg-my-pink hover:bg-red hover:opacity-80 flex items-center justify-center transition duration-250" do 
          
    
    %ul.flex.border-b.border-light-blue.text-sm.font-medium.text-my-blue.px-4.md:px-0.mt-8.w-auto
      %li.font-bold.hover:text-my-pink.cursor-pointer.tablink
        %a.py-4.inline-block.bold.hover:bg-my-pink.hover:text-my-blue.p-4 Students

    = render :partial => 'layouts/table_links'
    .divtab
      .flex.flex-col.md:flex-row.items-center.justify-between.w-full.mt-8
        %h1.text-2xl.font-bold.text-my-blue.px-6.md:px-0 Students
      .w-full.mt-10
        %table#students.min-w-full.divide-y.divide-gray-200.py-8
          %thead.bg-my-light-blue.dark:bg-white
            %tr
              %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Name
              %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Status
              %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Time Submitted
              %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"} Score
              %th.py-3.px-6.text-xs.font-medium.tracking-wider.text-left.text-gray-700.uppercase.dark:text-gray-400{scope: "col"}

          %tbody{class: "bg-white"}
            - @students.each do |student|
              %tr
                %td.py-4.px-6.text-sm.font-medium.text-gray-700.whitespace-nowrap.dark:text-white
                  = student.user.fullname
                %td.py-4.px-6.text-sm.font-medium.text-gray-700.whitespace-nowrap.dark:text-white
                  = student.my_submission(@activity).length == 0 ? "Not Viewed" : "Graded"
                %td.py-4.px-6.text-sm.font-medium.text-gray-700.whitespace-nowrap.dark:text-white
                  = student.my_submission(@activity).length == 0 ? "" : student.my_submission(@activity).first.created_at
                %td.py-4.px-6.text-sm.font-medium.text-gray-700.whitespace-nowrap.dark:text-white
                  = student.my_submission(@activity).length == 0 ? "" : student.my_score(@activity)
                %td.py-4.px-6.text-sm.font-medium.text-gray-700.whitespace-nowrap.dark:text-white
                  - unless student.my_submission(@activity).length == 0
                    = link_to "View", group_activity_activity_submission_path(@group, @activity, student.my_submission(@activity).first)

    -# .divtab{id: "Overview"}
    -#   .overview
    -#     .flex.justify-between
    -#       .groups-filter
    -#         = @group.name
    -#       %div
    -#         %span 
    -#           2 Graded
    -#         ·
    -#         %span 0 Ungraded
    -#         ·
    -#         %span 3 Not Turned In
    -#       .btn-tab
    -#         %button#print-btn.print-btn.qa-test-print-out.btn.btn-secondary{:type => "button"}
    -#           %svg{:height => "28", :name => "printer-icon", :viewbox => "0 0 24 24", :width => "28"}
    -#             %path{:d => "M16 15v-2H8v6h4v-4h4zm-1 2h-1v1l1-1zm-9 0H3v-6.364C3 9.733 3.733 9 4.636 9h14.728C20.267 9 21 9.733 21 10.636V17h-3l-4 4H6v-4zm.5-5h7a.5.5 0 100-1h-7a.5.5 0 100 1zm11 0a.5.5 0 100-1h-1a.5.5 0 100 1h1zM8 6v2H6V4h12v4h-2V6H8z", :fill => "#1c1e27", "fill-rule" => "evenodd", :id => "Icon/small/printer", :stroke => "none", "stroke-width" => "1"}
    -#     %hr/
    -#     .flex.justify-between
    -#       .score-card
    -#         .title-container
    -#           %p.score-title
    -#             %span Average Score
    -#         %p.percent
    -#           %span 50
    -#           %span %
    -#         %p.points-container
    -#         = succeed "\u{a0}" do
    -#           .progress-wrapper
    -#             %span.points 1.5
    -#             %span.total-points / 3
    -#         %span points
    -#       .score-card
    -#         .title-container
    -#           %p.score-title
    -#             %span Median Score
    -#         %p.percent
    -#           %span 50
    -#           %span %
    -#         %p.points-container
    -#         = succeed "\u{a0}" do
    -#           .progress-wrapper
    -#             %span.points 1.5
    -#             %span.total-points / 3
    -#         %span points
    -#       .score-card
    -#         .title-container
    -#           %p.score-title
    -#             %span Highest Score
    -#         %p.percent
    -#           %span 66
    -#           %span %
    -#         %p.points-container
    -#         = succeed "\u{a0}" do
    -#           .progress-wrapper
    -#             %span.points 2
    -#             %span.total-points / 3
    -#         %span points
    
    -# .divtab{id: "Assignments"}
    -#   = render 'assignments/index'  


:javascript
  var table = $('#students').DataTable( {
    responsive: true
  } )
  .columns.adjust()
  .responsive.recalc();

  function toggleModal() {
    document.getElementById('modal').classList.toggle('hidden')
  }